version: "3"
services:
  quote-service:
    image: quote-service
    platform: linux/amd64
    container_name: quote-service
    depends_on:
      - redis
    ports:
      - 8080:8080
    links:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379