version: "3"
services:
  user-service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/amd64
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: userservice
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
volumes:
  mysql-data:
